global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "esp32_env"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "192.168.1.50:80"  # ESP32 IP address
